{
	"version": 1581799089,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/joyback-sheet0.png",
		"images/joystick-sheet0.png",
		"images/brickfloor.png",
		"images/weapon-sheet0.png",
		"images/playereffectmask-sheet0.png",
		"images/interactbutton-sheet0.png",
		"images/interactbutton-sheet1.png",
		"images/interactbutton-sheet2.png",
		"images/enemy-sheet0.png",
		"images/blood-sheet0.png",
		"images/blood-sheet1.png",
		"images/blood-sheet2.png",
		"images/shottail-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}